default:
  image: maven:3.8.2-openjdk-11
  
stages:
  - check
  - build
  - test


check-version:
  stage: check
  script:
    - mvn --version


build:
  stage: build
  image: gradle:8.5-jdk17
  script:
     - cd src/ad
     - chmod +x gradlew
     - ./gradlew clean build

