
stages:
  - check
  - build
  - test


default:
  image: golang:1.22
  before_script:
    - cd src/product-catalog

# ---------------- BUILD ----------------
build:
  stage: build
  script:
    - go mod download
    - go build -o product-catalog-service main.go
  artifacts:
    paths:
      - src/product-catalog/product-catalog-service

